spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_repository
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: INFO
