spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_repository
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        defer-datasource-initialization: true

        cache:
          use_second_level_cache: true
          use_query_cache: true
          provider_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        javax:
          cache:
            missing_cache_strategy: create
        generate_statistics: false
  cache:
    ehcache:
      config: ehcache-config.xml

  messages:
    basename: messages
    fallback-to-system-locale: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1084978167683-2dhm70nl37gn3cb5evgejej69g6eg3ki.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

  mvc:
    format:
      date: iso
      time: iso
      date-time: iso
  servlet:
    multipart:
      location: C:\Users\LENOVO\IdeaProjects\Level_2\dmdev-project-level-2\images
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    oauth:
      client-id: 1084978167683-2dhm70nl37gn3cb5evgejej69g6eg3ki.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

logging:
  level:
    org.springframework.jdbc.core: TRACE
    rg.hibernate.cache.jcache.internal: TRACE