spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_repository
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: INFO